forms/teacher_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired, Length


class TeacherForm(FlaskForm):
    display_name = StringField("display_name", validators=[DataRequired(), Length(min=2, max=50)])
    username = StringField("username", validators=[DataRequired(), Length(min=8, max=20)])
    teacher_password = StringField(
        "teacher_password", validators=[DataRequired(), Length(min=8, max=100)]
    )
    is_admin = IntegerField("is_admin")

controllers/teacher_controller.py
"""Teacher controller with all its routes"""
from sqlite3 import Error
from flask import Blueprint, session, render_template, redirect, url_for, request
from flask_bcrypt import Bcrypt

from models.teacher_model import TeacherModel
from forms.teacher_form import TeacherForm

teachers_page = Blueprint(
    "teachers",
    __name__,
    url_prefix="/teachers",
    template_folder="templates/teacher",
    static_folder="static",
)

DATABASE_FILE = "databases/testgpt.db"


@teachers_page.route("/", methods=["GET", "POST"])
def teachers():
    """Teachers route which shows all the teachers from the database"""
    if session["is_admin"] == 1:
        teacher_model = TeacherModel(DATABASE_FILE)
        username = session["user"]
        select_teachers = teacher_model.get_all_teachers()

        return render_template(
            "teacher/teachers.html.j2", teachers=select_teachers, username=username
        )
    return redirect(url_for("dashboard"))


@teachers_page.route("/create_teacher", methods=["GET", "POST"])
def create_teacher():
    """Create teacher route that creates a teacher and inserts it into the database"""
    if session["is_admin"] == 1:
        teacher_model = TeacherModel(DATABASE_FILE)
        teacher_form = TeacherForm()
        bcrypt = Bcrypt()
        username = session["user"]
        if teacher_form.validate_on_submit():
            display_name = teacher_form.display_name.data
            username = teacher_form.username.data
            teacher_password = teacher_form.teacher_password.data
            is_admin = teacher_form.is_admin.data

            hashed_password = bcrypt.generate_password_hash(teacher_password)

            teacher_model.insert_teacher(
                display_name=display_name,
                username=username,
                teacher_password=hashed_password,
                is_admin=is_admin,
            )

            return redirect(url_for("teachers.teachers"))
        return render_template(
            "teacher/create_teacher.html.j2", username=username, form=teacher_form
        )
    return redirect(url_for("dashboard"))


@teachers_page.route("/delete_teacher", methods=["GET", "POST"])
def delete_teacher():
    """Delete teacher route that deletes a specific teacher from the database"""
    if session["is_admin"] == 1:
        teacher_model = TeacherModel(DATABASE_FILE)
        if request.method == "POST":
            try:
                teacher_id = request.form["teacher_id"]
                teacher_model.delete_teacher(teacher_id=teacher_id)

            except Error as error:
                print(error)

        return redirect(url_for("teachers.teachers"))

    return redirect(url_for("dashboard"))


@teachers_page.route("/search_teacher", methods=["GET", "POST"])
def search_teacher():
    """Searches for a specific teacher if the search value aligns with their name or username and
    selects them from the database"""
    if session["is_admin"] == 1:
        result = None
        teacher_model = TeacherModel(DATABASE_FILE)
        username = session["user"]
        select_teachers = teacher_model.get_all_teachers()
        if request.method == "POST":
            try:
                search_value = request.form["search_value"]

                result = teacher_model.search_teacher(search_value=search_value)
            except Error as error:
                print(error)

        return render_template(
            "teacher/teachers.html.j2",
            result=result,
            teachers=select_teachers,
            username=username,
        )
    return redirect(url_for("login"))


@teachers_page.route("/edit_teacher", methods=["POST", "GET"])
def edit_teacher():
    """Edit teacher route that edits the changed fields from the teacher into the database"""
    if session["is_admin"] == 1:
        bcrypt = Bcrypt()
        teacher_model = TeacherModel(DATABASE_FILE)
        if request.method == "POST":
            try:
                display_name = request.form["display_name"]
                username = request.form["username"]
                teacher_password = request.form["teacher_password"]
                is_admin = request.form["is_admin"]
                teacher_id = request.form["teacher_id"]
                hashed_password = bcrypt.generate_password_hash(teacher_password)
                teacher_model.update_teacher(
                    display_name=display_name,
                    username=username,
                    teacher_password=hashed_password,
                    is_admin=is_admin,
                    teacher_id=teacher_id,
                )
            except Error as error:
                print(error)

        return redirect(url_for("teachers.teachers"))

    return redirect(url_for("login"))


@teachers_page.route("/profile", methods=["GET", "POST"])
def profile():
    if "user" in session:
        admin = session["is_admin"]
        display_name = session["display_name"]
        username = session["user"]

        return render_template(
            "teacher/profile.html.j2",
            display_name=display_name,
            username=username,
            admin=admin,
        )


@teachers_page.route("/teacher/<int:teacher_id>", methods=["POST", "GET"])
def teacher(teacher_id):
    if session["is_admin"] == 1:
        selected_teacher = None
        teacher_model = TeacherModel(DATABASE_FILE)
        username = session["user"]
        if request.method == "POST":
            try:
                teacher_id = request.form["teacher_id"]
                selected_teacher = teacher_model.select_teacher(teacher_id=teacher_id)
            except Error as error:
                print(error)
        return render_template(
            "teacher/teacher.html.j2",
            teacher=selected_teacher,
            teacher_id=teacher_id,
            username=username,
        )

    return redirect(url_for("login"))

templates/teacher/create_teacher.html.j2
{% extends "index.html.j2" %}
{% block content %}
<form action="{{ url_for('teachers.create_teacher') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="border-b border-gray-900/10 pb-12">
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-3">
                    <label for="display_name" class="block font-medium leading-6 text-gray-900">Display Name</label>
                    <div class="mt-2">
                        <label>
                        <input type="text" id="display_name" name="display_name" placeholder="Diederik de Vries" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                    {% if form.display_name.errors %}
                    {% for error in form.display_name.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="sm:col-span-3">
                    <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
                    <div class="mt-2">
                        <label>
                        <input type="text" name="username" placeholder="diederiknl" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="sm:col-span-3">
                    <label for="teacher_password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
                    <div class="mt-2">
                        <label>
                        <input name="teacher_password" type="text" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                    {% if form.teacher_password.errors %}
                    {% for error in form.teacher_password.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="sm:col-span-3">
                    <label for="is_admin" class="block text-sm font-medium leading-6 text-gray-900">Admin</label>
                    <div class="mt-2">
                        <label>
                            <select name="is_admin"  class="block w-full pl-2 rounded-md border-0 py-2.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                                <option value="1">Yes</option>
                                <option value="0">No</option>
                            </select>
                        </label>
                    </div>
                    {% if form.is_admin.errors %}
                    {% for error in form.is_admin.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ url_for('teachers.teachers') }}" class="href">
                <button type="button" class="border rounded-lg text-red-500 px-3 py-2 text-sm font-semibold shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Cancel</button>
            </a>
            <button type="submit" class="rounded-lg bg-green-500 text-white px-3 py-2 text-sm font-semibold shadow-sm hover:bg-green-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Save</button>
        </div>
    </div>
</form>
{% endblock %}

templates/teacher/profile.html.j2
{% extends "index.html.j2" %}
{% block content %}
<div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <form>
        <div class="space-y-12">
            <div class="border-b border-gray-900/10 pb-12 py-8">
                <div>
                    <h2 class="text-2xl font-semibold leading-tight">Profile of {{ display_name }}</h2>
                </div>
            </div>
            <div class="border-b border-gray-900/10 pb-12">
                <h2 class="text-base font-semibold leading-7 text-gray-900">Personal Information</h2>
                <p class="mt-1 text-sm leading-6 text-gray-600">Use a permanent address where you can receive mail.</p>
                <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                    <div class="sm:col-span-3">
                    <label for="display_name" class="block font-medium leading-6 text-gray-900">Name</label>
                    <div class="mt-2">
                        <label>
                        <input type="text" id="display_name" name="display_name" value="{{ display_name }}" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
                    <div class="mt-2">
                        <label>
                        <input type="text" name="username" value="{{ username }}" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="teacher_password" class="block text-sm font-medium leading-6 text-gray-900">Admin</label>
                    <div class="mt-2">
                        <label>
                        <input name="teacher_password" type="text" value="{% if admin == 1 %}Yes{% else %}No{% endif %}" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                </div>
            </div>
        </div>

        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ url_for('teachers.teachers') }}" class="href">
                <button type="button" class="border rounded-lg text-red-500 px-3 py-2 text-sm font-semibold shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Cancel</button>
            </a>
            <button type="submit" class="rounded-lg bg-green-500 text-white px-3 py-2 text-sm font-semibold shadow-sm hover:bg-green-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Save</button>
        </div>
    </form>
</div>
{% endblock %}

templates/teacher/teacher.html.j2
{% extends "index.html.j2" %}
{% block content %}
{% for teacher in teacher %}
<form action="{{ url_for('teachers.edit_teacher') }}" method="POST">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="border-b border-gray-900/10 pb-12">
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-3">
                    <label for="display_name" class="block font-medium leading-6 text-gray-900">Display Name</label>
                    <div class="mt-2">
                        <label>
                        <input value={{ teacher.display_name }} type="text" id="display_name" name="display_name" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
                    <div class="mt-2">
                        <label>
                        <input value={{ teacher.username }} type="text" name="username" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="teacher_password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
                    <div class="mt-2">
                        <label>
                        <input value={{ teacher.teacher_password }} name="teacher_password" type="password" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <input type="hidden" name="teacher_id" value="{{ teacher.teacher_id }}" >
                <div class="sm:col-span-3">
                    <label for="is_admin" class="block text-sm font-medium leading-6 text-gray-900">Admin</label>
                    <div class="mt-2">
                        <label>
                            <select name="is_admin" class="block w-full pl-2 rounded-md border-0 py-2.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-700 sm:text-sm sm:leading-6">
                                <option value="{{ teacher.is_admin }}">{{ teacher.is_admin }}</option>
                                <option value="1"> 1 </option>
                                <option value="0"> 0 </option>
                            </select>
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ url_for('teachers.teachers') }}" class="href">
                <button type="button" class="border rounded-lg text-red-500 px-3 py-2 text-sm font-semibold shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Cancel</button>
            </a>
            <button type="submit" class="rounded-lg bg-green-500 text-white px-3 py-2 text-sm font-semibold shadow-sm hover:bg-green-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Save</button>
        </div>
    </div>
</form>
{% endfor %}
{% endblock %}