forms/category_form.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length


class CategoryForm(FlaskForm):
    omschrijving = StringField("omschrijving", validators=[DataRequired(), Length(min=3, max=30)])

controllers/category_controller.py
"""Category Controller with all its routes"""
from sqlite3 import Error
from flask import Blueprint, request, render_template, redirect, url_for, session

from models.category_model import CategoryModel
from forms.category_form import CategoryForm

category_page = Blueprint(
    "category",
    __name__,
    url_prefix="/categories",
    template_folder="templates/category",
    static_folder="static",
)

DATABASE_FILE = "databases/testgpt.db"


@category_page.route("/create_category", methods=["GET", "POST"])
def create_category():
    """Create category route that inserts the data from the category form in the database"""
    if "user" in session:
        username = session["user"]
        category_form = CategoryForm()
        category_model = CategoryModel(DATABASE_FILE)
        if category_form.validate_on_submit():
            omschrijving = category_form.omschrijving.data
            category_model.insert_category(omschrijving=omschrijving)
            return redirect(url_for("category.categories"))

        return render_template(
            "category/create_category.html.j2", form=category_form, username=username
        )
    return redirect(url_for("login"))


@category_page.route("/")
def categories():
    """Categories route that displays all the categories in the database"""
    if "user" in session:
        category_model = CategoryModel(DATABASE_FILE)
        username = session["user"]
        select_categories = category_model.get_all_categories()
        return render_template(
            "category/categories.html.j2",
            categories=select_categories,
            username=username,
        )
    return redirect(url_for("login"))


@category_page.route("/delete_category", methods=["POST", "GET"])
def delete_category():
    """Delete category route that deletes a specific categpry from the database"""
    if "user" in session:
        category_model = CategoryModel(DATABASE_FILE)
        if request.method == "POST":
            try:
                category_id = request.form["category_id"]

                category_model.delete_category(category_id=category_id)
            except Error as error:
                print(error)
        return redirect(url_for("category.categories"))
    return redirect(url_for("login"))


@category_page.route("/category/<int:category_id>", methods=["POST", "GET"])
def category(category_id):
    """Category route that selects a specific category and displays it in the form"""
    if "user" in session:
        selected_category = None
        category_model = CategoryModel(DATABASE_FILE)
        username = session["user"]
        if request.method == "POST":
            try:
                category_id = request.form["category_id"]
                selected_category = category_model.select_category(category_id=category_id)
            except Error as error:
                print(error)
        return render_template(
            "category/category.html.j2",
            category=selected_category,
            category_id=category_id,
            username=username,
        )
    return redirect(url_for("login"))


@category_page.route("/update_category", methods=["POST", "GET"])
def update_category():
    """Update category route that updates the changed fields in the database"""
    if "user" in session:
        username = session["user"]
        category_model = CategoryModel(DATABASE_FILE)
        if request.method == "POST":
            try:
                category_id = request.form["category_id"]
                omschrijving = request.form["omschrijving"]

                category_model.update_category(category_id=category_id, omschrijving=omschrijving)
                return redirect(url_for("category.categories"))
            except Error as error:
                print(error)
        return render_template("category/category.html.j2", username=username)
    return redirect(url_for("login"))


@category_page.route("/search_category", methods=["POST", "GET"])
def search_category():
    """Search category route that searches the category table and displays one or more categories
    if they align with the search input"""
    if "user" in session:
        result = None
        category_model = CategoryModel(DATABASE_FILE)
        username = session["user"]
        select_categories = category_model.get_all_categories()
        if request.method == "POST":
            try:
                search_value = request.form["search_value"]

                result = category_model.search_categories(search_value=search_value)
            except Error as error:
                print(error)

        return render_template(
            "category/categories.html.j2",
            result=result,
            categories=select_categories,
            username=username,
        )
    return redirect(url_for("login"))

templates/category/categories.html.j2
{% extends "index.html.j2" %}
{% block content %}
<div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="py-8">
        <div class="mb-5">
            <h2 class="text-2xl font-semibold leading-tight">Categories</h2>
        </div>
        <div class="my-2 flex sm:flex-row flex-col">
            <div class="block relative">
                <form action="{{ url_for('category.search_category') }}" method="POST">
                    <label>
                    <input placeholder="Search"
                        name="search_value" class="appearance-none rounded-e-lg rounded-s-lg border border-gray-200 border-b block pl-8 pr-6 py-2 w-full bg-white placeholder-gray-400 text-gray-700 focus:bg-white focus:placeholder-gray-600 focus:text-gray-700 focus:outline-none" />
                    </label>
                    <span class="h-full absolute inset-y-0 right-0 flex items-center pl-2">
                        <button
                            type="submit"
                            class="hover:bg-gray-100 rounded-s-none rounded-e-lg text-gray-700 rounded-md px-3 py-1.5 transition duration-500 ease select-none hover:bg-gray-200 focus:outline-none focus:shadow-outline"
                            >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"></path>
                            </svg>
                        </button>
                    </span>
                </form>
            </div>
            <div class="block relative">
                <span class="h-full absolute inset-y-0 left-0 flex items-center pl-2">
                    <form action="{{ url_for('category.create_category') }}">
                        <button
                            type="submit"
                            class="border-green-500 bg-green-500 text-white rounded-md px-3 py-1.5 m-2 transition duration-500 ease select-none hover:bg-green-600 focus:outline-none focus:shadow-outline"
                            >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15"></path>
                            </svg>
                        </button>
                    </form>
                </span>
            </div>
        </div>
        <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
            <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                <table class="min-w-full divide-y divide-gray-200 text-sm">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-xs text-left font-medium text-gray-500 uppercase tracking-wider">
                                Omschrijving
                            </th>
                            <th scope="col" class="px-6 py-3 text-xs text-left font-medium text-gray-500 uppercase tracking-wider">
                                Created at
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Delete</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {% if result | length != 0 %}
                        {% for category in result %}
                        <tr>
                            <td class="px-6 py-4 whitespace-nowrap text-gray-700">
                                {{ category.omschrijving }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-gray-500">
                                {{ category.date_created }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-right font-medium">
                                <form action="{{ url_for('category.category', category_id=category.category_id) }}" method="POST">
                                    <input type="hidden" name="category_id" value="{{ category.category_id }}" >
                                    <button type="submit" class="hover:bg-gray-100 border text-gray-700 py-2 px-3 rounded-s-lg rounded-e-lg">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
                                        </svg>
                                    </button>
                                </form>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-right font-medium">
                                <form action="{{ url_for('category.delete_category')}}" method="POST">
                                    <input type="hidden" value="{{ category.category_id }}" name="category_id">
                                    <button type="submit" class="hover:bg-gray-100 border text-gray-700 py-2 px-3 rounded-s-lg rounded-e-lg">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"></path>
                                        </svg>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        {% for category in categories %}
                        <tr>
                            <td class="px-6 py-4 whitespace-nowrap text-gray-700">
                                {{ category.omschrijving }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-gray-500">
                                {{ category.date_created }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-right font-medium">
                                <form action="{{ url_for('category.category', category_id=category.category_id) }}" method="POST">
                                    <input type="hidden" name="category_id" value="{{ category.category_id }}" >
                                    <button type="submit" class="hover:bg-gray-100 border text-gray-700 py-2 px-3 rounded-s-lg rounded-e-lg">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
                                        </svg>
                                    </button>
                                </form>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-right font-medium">
                                <form action="{{ url_for('category.delete_category')}}" method="POST">
                                    <input type="hidden" value="{{ category.category_id }}" name="category_id">
                                    <button type="submit" class="hover:bg-gray-100 border text-gray-700 py-2 px-3 rounded-s-lg rounded-e-lg">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"></path>
                                        </svg>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
                <div
                    class="px-5 py-5 bg-white border-t flex flex-col xs:flex-row items-center xs:justify-between">
                    <span class="text-gray-900">
                    Showing 1 to 4 of 50 Entries
                    </span>
                    <div class="inline-flex mt-2 xs:mt-0">
                        <button
                            class="hover:bg-gray-100 border text-gray-700 py-2 px-4 rounded-s-lg">
                        Previous
                        </button>
                        <button
                            class="hover:bg-gray-100 border text-gray-700 py-2 px-4 rounded-e-lg">
                        Next
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/category/category.html.j2
{% extends "index.html.j2" %}
{% block content %}
{% for category in category %}
<form action="{{ url_for('category.update_category') }}"  method="POST">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="border-b border-gray-900/10 pb-12">
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-3">
                    <label for="omschrijving" class="block font-medium leading-6 text-gray-900">Omschrijving</label>
                    <div class="mt-2">
                        <label>
                        <input type="text" name="omschrijving" value="{{ category.omschrijving }}"  class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="date_created" class="block font-medium leading-6 text-gray-900">Created At</label>
                    <div class="mt-2">
                        <label>
                        <input type="text" name="date_created" disabled value="{{ category.date_created }}"  class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <label>
                <input type="hidden" name="category_id" value="{{ category.category_id }}" >
                </label>
            </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ url_for('category.categories') }}" class="href">
                <button type="button" class="border rounded-lg text-red-500 px-3 py-2 text-sm font-semibold shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Cancel</button>
            </a>
            <button type="submit" class="rounded-lg bg-green-500 text-white px-3 py-2 text-sm font-semibold shadow-sm hover:bg-green-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Save</button>
        </div>
    </div>
</form>
{% endfor %}
{% endblock %}

templates/category/create_category.html.j2
{% extends "index.html.j2" %}
{% block content %}
<form action="{{ url_for('category.create_category') }}" method="POST">
    {# dit is de csrf token #}
    {{ form.hidden_tag() }}
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="border-b border-gray-900/10 pb-12">
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-3">
                    <label for="omschrijving" class="block font-medium leading-6 text-gray-900">Omschrijving</label>
                    <div class="mt-2">
                        <label>
                        <input id="omschrijving" name="omschrijving" placeholder="eg: Databases" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                    {% if form.omschrijving.errors %}
                    {% for error in form.omschrijving.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
           <a href="{{ url_for('category.categories') }}" class="href">
                <button type="button" class="border rounded-lg text-red-500 px-3 py-2 text-sm font-semibold shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Cancel</button>
            </a>
            <button type="submit" class="rounded-lg bg-green-500 text-white px-3 py-2 text-sm font-semibold shadow-sm hover:bg-green-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Save</button>
        </div>
    </div>
</form>
{% endblock %}