forms/note_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField
from wtforms.validators import Optional, DataRequired, Length


class NoteForm(FlaskForm):
    title = StringField("title", validators=[Optional()])
    note_source = StringField("note_source", validators=[DataRequired(), Length(min=4, max=100)])
    is_public = IntegerField("is_public")
    teacher_id = IntegerField("teacher_id", validators=[DataRequired()])
    category_id = IntegerField("category_id", validators=[DataRequired()])
    note = StringField("note", validators=[DataRequired(), Length(min=10, max=1500)])

controllers/note_controller.py
"""Note controller with all its routes"""
from sqlite3 import Error
import os

from flask import Blueprint, request, render_template, redirect, url_for, session

from models.category_model import CategoryModel
from models.note_model import NoteModel
from models.teacher_model import TeacherModel
from models.question_model import QuestionModel
from forms.note_form import NoteForm
from lib.testgpt.testgpt import TestGPT

notes_page = Blueprint(
    "notes",
    __name__,
    url_prefix="/notes",
    template_folder="templates/note",
    static_folder="static",
)

DATABASE_FILE = "databases/testgpt.db"


@notes_page.route("/create_note", methods=["POST", "GET"])
def create_note():
    """Create note route that creates a new note and inserts it into the database"""
    if "user" in session:
        note_model = NoteModel(DATABASE_FILE)
        teacher_model = TeacherModel(DATABASE_FILE)
        category_model = CategoryModel(DATABASE_FILE)
        username = session["user"]
        note_form = NoteForm()
        select_categories = category_model.get_all_categories()
        select_teachers = teacher_model.get_all_teachers()
        if note_form.validate_on_submit():
            title = note_form.title.data
            note_source = note_form.note_source.data
            is_public = note_form.is_public.data
            teacher_id = note_form.teacher_id.data
            category_id = note_form.category_id.data
            note_text = note_form.note.data

            note_model.insert_note(
                title=title,
                note_source=note_source,
                is_public=is_public,
                teacher_id=teacher_id,
                category_id=category_id,
                note=note_text,
            )
            return redirect(url_for("notes.notes"))
        return render_template(
            "note/create_note.html.j2",
            categories=select_categories,
            teachers=select_teachers,
            form=note_form,
            username=username,
        )

    return redirect(url_for("login"))


@notes_page.route("/delete_note", methods=["GET", "POST"])
def delete_note():
    """Delete note route that deletes a specific note from the database"""
    if "user" in session:
        note_model = NoteModel(DATABASE_FILE)
        if request.method == "POST":
            try:
                note_id = request.form["note_id"]
                note_model.delete_note(note_id=note_id)

            except Error as error:
                print(error)

        return redirect(url_for("notes.notes"))

    return redirect(url_for("login"))


@notes_page.route("/note/<int:note_id>", methods=["POST", "GET"])
def note(note_id):
    """Note route that displays a sepcific note from the database"""
    if "user" in session:
        note_model = NoteModel(DATABASE_FILE)
        teacher_model = TeacherModel(DATABASE_FILE)
        category_model = CategoryModel(DATABASE_FILE)
        question_model = QuestionModel(DATABASE_FILE)
        username = session["user"]
        select_note = None
        select_question = None
        select_categories = category_model.get_all_categories()
        select_teachers = teacher_model.get_all_teachers()
        if request.method == "POST":
            try:
                note_id = request.form["note_id"]
                select_note = note_model.select_note(note_id=note_id)
                select_question = question_model.select_question_by_note(note_id=note_id)
            except Error as error:
                print(error)
        return render_template(
            "note/note.html.j2",
            note=select_note,
            teachers=select_teachers,
            categories=select_categories,
            questions=select_question,
            note_id=note_id,
            username=username,
        )

    return redirect(url_for("login"))


@notes_page.route("/edit_note", methods=["POST", "GET"])
def edit_note():
    """Edit note route that updates the changed fields from the note into the database"""
    if "user" in session:
        note_model = NoteModel(DATABASE_FILE)
        if request.method == "POST":
            try:
                title = request.form["title"]
                note_source = request.form["note_source"]
                is_public = request.form["is_public"]
                teacher_id = request.form["teacher_id"]
                category_id = request.form["category_id"]
                note_id = request.form["note_id"]
                note_text = request.form["note"]
                note_model.update_note(
                    title=title,
                    note_source=note_source,
                    is_public=is_public,
                    teacher_id=teacher_id,
                    category_id=category_id,
                    note=note_text,
                    note_id=note_id,
                )
            except Error as error:
                print(error)

        return redirect(url_for("notes.notes"))

    return redirect(url_for("login"))


@notes_page.route("/search_note", methods=["POST", "GET"])
def search_note():
    if "user" in session:
        result = None
        note_model = NoteModel(DATABASE_FILE)
        category_model = CategoryModel(DATABASE_FILE)
        username = session["user"]
        teacher_id = session["teacher_id"]
        select_notes = note_model.get_all_notes(teacher_id=str(teacher_id))
        select_categories = category_model.get_all_categories()

        if request.method == "POST":
            try:
                search_value = request.form["search_value"]
                page = request.args.get("page", default=1, type=int)
                entries_per_page = 20
                offset = (page - 1) * entries_per_page

                result = note_model.search_note(
                    teacher_id=str(teacher_id),
                    search_value=str(search_value),
                    offset=offset,
                    limit=entries_per_page,
                )

                total_entries = len(result) if result else len(select_notes)

                return render_template(
                    "note/notes.html.j2",
                    result=result,
                    notes=select_notes,
                    categories=select_categories,
                    username=username,
                    page=page,
                    entries_per_page=entries_per_page,
                    total_entries=total_entries,
                )

            except Error as error:
                print(error)

        return render_template(
            "note/notes.html.j2",
            result=result,
            notes=select_notes,
            categories=select_categories,
            username=username,
            page=1,
            entries_per_page=20,
            total_entries=len(result) if result else len(select_notes),
        )

    return redirect(url_for("login"))


@notes_page.route("/filter_note_by_category", methods=["POST", "GET"])
def filter_note_by_category():
    """Filter note route that filters the notes based on category that they belong to"""
    if "user" in session:
        result = None
        note_model = NoteModel(DATABASE_FILE)
        category_model = CategoryModel(DATABASE_FILE)
        username = session["user"]
        teacher_id = session["teacher_id"]
        select_notes = note_model.get_all_notes(teacher_id=str(teacher_id))
        select_categories = category_model.get_all_categories()
        if request.method == "POST":
            try:
                filter_value = request.form["filter_value"]
                page = request.args.get("page", default=1, type=int)
                entries_per_page = 20
                offset = (page - 1) * entries_per_page

                result = note_model.filter_note_by_category(
                    teacher_id=str(teacher_id),
                    filter_value=filter_value,
                    offset=offset,
                    limit=entries_per_page,
                )

                total_entries = len(result) if result else len(select_notes)

                return render_template(
                    "note/notes.html.j2",
                    result=result,
                    notes=select_notes,
                    categories=select_categories,
                    username=username,
                    page=page,
                    entries_per_page=entries_per_page,
                    total_entries=total_entries,
                )

            except Error as error:
                print(error)

        return render_template(
            "note/notes.html.j2",
            result=result,
            notes=select_notes,
            categories=select_categories,
            username=username,
            page=1,
            entries_per_page=20,
            total_entries=len(result) if result else len(select_notes),
        )

    return redirect(url_for("login"))


@notes_page.route("/filter_note_by_teacher", methods=["POST", "GET"])
def filter_note_by_teacher():
    if "user" in session:
        result = None
        note_model = NoteModel(DATABASE_FILE)
        username = session["user"]
        teacher_id = session["teacher_id"]
        select_notes = note_model.get_all_notes(teacher_id=str(teacher_id))

        if request.method == "POST":
            try:
                page = request.args.get("page", default=1, type=int)
                entries_per_page = 20
                offset = (page - 1) * entries_per_page

                result = note_model.filter_note_by_teacher(offset=offset, limit=entries_per_page)

                total_entries = len(result) if result else len(select_notes)

                return render_template(
                    "note/notes.html.j2",
                    result=result,
                    notes=select_notes,
                    username=username,
                    page=page,
                    entries_per_page=entries_per_page,
                    total_entries=total_entries,
                )

controllers/questions_controller.py
from sqlite3 import Error
from controllers.database_connector import DatabaseConnector


class QuestionsController(DatabaseConnector):
    database = DatabaseConnector()
    cursor = database.connect().cursor()

    @staticmethod
    def select_questions():
        QuestionsController.database.connect()
        try:
            QuestionsController.cursor.execute(
                "SELECT * FROM questions INNER JOIN notes ON notes.note_id = questions.note_id")
            QuestionsController.cursor.connection.commit()
            questions = QuestionsController.cursor.fetchall()
            print(questions)
            return questions
        except Error as error:
            print(error)

    @staticmethod
    def insert_question(note_id, exam_question):
        QuestionsController.database.connect()
        try:
            QuestionsController.cursor.execute(
                "INSERT INTO questions (note_id, exam_question) VALUES(?,?)", [note_id, exam_question])
            QuestionsController.cursor.connection.commit()
            return QuestionsController.cursor.lastrowid
        except Error as error:
            print(error)

    @staticmethod
    def delete_question(note_id):
        QuestionsController.database.connect()
        try:
            QuestionsController.cursor.execute(
                "DELETE FROM exam_questions WHERE note_id=" + note_id)
            QuestionsController.cursor.connection.commit()
        except Error as error:
            print(error)

    @staticmethod
    def generate_question(note_id, question):
        QuestionsController.database.connect()
        try:
            QuestionsController.cursor.execute("UPDATE questions SET exam_question = '" + question + "' WHERE " +
                                               "note_id=" + note_id)
            QuestionsController.cursor.connection.commit()
            return QuestionsController.cursor.fetchone()
        except Error as error:
            print(error)

templates/note/create_note.html.j2
{% extends "index.html.j2" %}
{% block content %}
<form action="{{ url_for('notes.create_note') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="border-b border-gray-900/10 pb-12">
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-3">
                    <label for="title" class="block font-medium leading-6 text-gray-900">Title</label>
                    <div class="mt-2">
                        <label>
                        <input id="title" name="title" placeholder="Summary of python OOP" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                    {% if form.title.errors %}
                    {% for error in form.title.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="sm:col-span-3">
                    <label for="note_source" class="block text-sm font-medium leading-6 text-gray-900">Note Source</label>
                    <div class="mt-2">
                        <label>
                        <input type="text" name="note_source" placeholder="eg: www.w3schools.com" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                    {% if form.note_source.errors %}
                    {% for error in form.note_source.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="sm:col-span-3">
                    <label for="is_public" class="block text-sm font-medium leading-6 text-gray-900">Is Public</label>
                    <div class="mt-2">
                        <label>
                            <select name="is_public"  class="block w-full pl-2 rounded-md border-0 py-2.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                                <option value="{{ 1 }}">Yes</option>
                                <option value="{{ 0 }}">No</option>
                            </select>
                        </label>
                    </div>
                    {% if form.is_public.errors %}
                    {% for error in form.is_public.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="sm:col-span-3">
                    <label for="teacher-id" class="block text-sm font-medium leading-6 text-gray-900">Teacher</label>
                    <div class="mt-2">
                        <label>
                            <select name="teacher_id"  class="block w-full pl-2 rounded-md border-0 py-2.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                                {% for teacher in teachers %}
                                <option value="{{ teacher[0] }}">{{ teacher[1] }}</option>
                                {% endfor %}
                            </select>
                        </label>
                    </div>
                    {% if form.teacher_id.errors %}
                    {% for error in form.teacher_id.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="sm:col-span-3">
                    <label for="category_id" class="block text-sm font-medium leading-6 text-gray-900">Category</label>
                    <div class="mt-2">
                        <label>
                            <select name="category_id" class="block w-full pl-2 rounded-md border-0 py-2.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                                {% for category in categories %}
                                <option value="{{ category[0] }}">{{ category[1] }}</option>
                                {% endfor %}
                            </select>
                        </label>
                    </div>
                    {% if form.category_id.errors %}
                    {% for error in form.category_id.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="sm:col-span-3">
                    <label for="note" class="block text-sm font-medium leading-6 text-gray-900">Note</label>
                    <div class="mt-2">
                        <label>
                        <textarea name="note" placeholder="Object-oriented programming (OOP) is a method of structuring a program by bundling related properties and behaviors into individual objects. In this tutorial, you’ll learn the basics of object-oriented programming in Python." class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"></textarea>
                        </label>
                    </div>
                    {% if form.note.errors %}
                    {% for error in form.note.errors %}
                    <p class="text-red-500 mt-1">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ url_for('notes.notes') }}" class="href">
                <button type="button" class="border rounded-lg text-red-500 px-3 py-2 text-sm font-semibold shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Cancel</button>
            </a>
            <button type="submit" class="rounded-lg bg-green-500 text-white px-3 py-2 text-sm font-semibold shadow-sm hover:bg-green-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Save</button>
        </div>
    </div>
</form>
{% endblock %}

templates/note/note.html.j2
{% extends "index.html.j2" %}
{% block content %}
{% for note in note %}
<form action="{{ url_for('notes.edit_note') }}"  method="POST">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="border-b border-gray-900/10 pb-12">
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-3">
                    <label for="title" class="block font-medium leading-6 text-gray-900">Title</label>
                    <div class="mt-2">
                        <label>
                        <input type="text" name="title" value="{{ note.title }}"  class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-700 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="note_source" class="block text-sm font-medium leading-6 text-gray-900">Note Source</label>
                    <div class="mt-2">
                        <label>
                        <input type="text" name="note_source" value="{{ note.note_source }}" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-700 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="is_public" class="block text-sm font-medium leading-6 text-gray-900">Is Public</label>
                    <div class="mt-2">
                        <label>
                            <select name="is_public"  class="block w-full pl-2 rounded-md border-0 py-2.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-700 sm:text-sm sm:leading-6">
                                <option value="{{ note.is_public }}">
                                    {% if note.is_public == 1 %}
                                    Yes
                                    {% else %}
                                    No
                                    {% endif %}
                                </option>
                                <option value="{{ 1 }}">Yes</option>
                                <option value="{{ 0 }}">No</option>
                            </select>
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="teacher_id" class="block text-sm font-medium leading-6 text-gray-900">Teacher</label>
                    <div class="mt-2">
                        <label>
                            <select name="teacher_id"  class="block w-full pl-2 rounded-md border-0 py-2.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-700 sm:text-sm sm:leading-6">
                                <option value="{{ note.teacher_id }}">{{ note.display_name }}</option>
                                {% for teacher in teachers %}
                                <option name="teacher_id" value="{{ teacher.teacher_id }}">{{ teacher.display_name }}</option>
                                {% endfor %}
                            </select>
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="category_id" class="block text-sm font-medium leading-6 text-gray-900">Category</label>
                    <div class="mt-2">
                        <label>
                            <select name="category_id" class="block w-full pl-2 rounded-md border-0 py-2.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-700 sm:text-sm sm:leading-6">
                                <option value="{{ note.category_id }}">{{ note.omschrijving }}</option>
                                {% for category in categories %}
                                <option value="{{ category.category_id }}">{{ category.omschrijving }}</option>
                                {% endfor %}
                            </select>
                        </label>
                    </div>
                </div>
                <div class="sm:col-span-3">
                    <label for="note" class="block text-sm font-medium leading-6 text-gray-900">Note</label>
                    <div class="mt-2">
                        <label>
                        <input name="note" value="{{ note.note }}" class="block w-full pl-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-700 sm:text-sm sm:leading-6">
                        </label>
                    </div>
                </div>
                <label>
                <input type="hidden" name="note_id" value="{{ note.note_id }}" >
                </label>
            </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ url_for('notes.notes') }}" class="href">
            <button type="button" class="border rounded-lg text-red-500 px-3 py-2 text-sm font-semibold shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Cancel</button>
            </a>
            <button type="submit" class="rounded-lg bg-green-500 text-white px-3 py-2 text-sm font-semibold shadow-sm hover:bg-green-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Save</button>
        </div>
    </div>
</form>
<div class="-mt-14 mx-auto max-w-7xl sm:px-6 lg:px-8">
    <div class="flex items-center justify-start gap-x-6">
        <form action="{{ url_for('notes.generate_question') }}" method="POST">
            <input type="hidden" name="note_id" value="{{ note.note_id }}">
            <input type="hidden" name="note" value="{{ note.note }}">
            <div class="mt-6">
                <button class="rounded-lg bg-black px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 inline-flex items-center"
                    type="submit"
                    >
                    <span class="pr-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z"></path>
                        </svg>
                    </span>
                    <span>Generate Open Question with AI</span>
                </button>
            </div>
        </form>

{#        <form action="{{ url_for('notes.generate_question') }}" method="POST">#}
            <input type="hidden" name="note_id" value="{{ note.note_id }}">
            <input type="hidden" name="note" value="{{ note.note }}">
            <div class="mt-6">
                <button class="rounded-lg bg-black px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 inline-flex items-center"
                    type="submit"
                    >
                    <span class="pr-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z"></path>
                        </svg>
                    </span>
                    <span>Generate Multiple Choice Question with AI</span>
                </button>
            </div>
{#        </form>#}
    </div>

    <ul role="list" class="">
        {% if questions | length != 0 %}
        <div class="mt-4">
            <h2 class="text-2xl font-semibold leading-tight">Questions</h2>
        </div>
        {% for question in questions %}
        <li class="flex justify-between gap-x-6 py-4 border rounded-lg px-4 mt-4">
            <div class="flex min-w-0 gap-x-4">
                <div class="min-w-0 flex-auto">
                    <p class="text-sm font-semibold leading-6 text-gray-900">{{ question.exam_question }}</p>
                    <p class="mt-1 truncate text-xs leading-5 text-gray-500">{{ question.note }}</p>
                </div>
            </div>
            <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
                <p class="text-sm leading-6 text-gray-900">
                    Made by: {{ question.display_name }}
                </p>
                <p class="mt-1 text-xs leading-5 text-gray-500">Added at: {{ question.date_created }}</p>
            </div>
        </li>
        {% endfor %}
        {% else %}
        {% endif %}
    </ul>
</div>
{% endfor %}
{% endblock %}