controllers/teacher_controller.py
"""Teacher controller with all its routes"""
from sqlite3 import Error
from flask import Blueprint, session, render_template, redirect, url_for, request
from flask_bcrypt import Bcrypt

from models.teacher_model import TeacherModel
from forms.teacher_form import TeacherForm

teachers_page = Blueprint(
    "teachers",
    __name__,
    url_prefix="/teachers",
    template_folder="templates/teacher",
    static_folder="static",
)

DATABASE_FILE = "databases/testgpt.db"


@teachers_page.route("/", methods=["GET", "POST"])
def teachers():
    """Teachers route which shows all the teachers from the database"""
    if session["is_admin"] == 1:
        teacher_model = TeacherModel(DATABASE_FILE)
        username = session["user"]
        select_teachers = teacher_model.get_all_teachers()

        return render_template(
            "teacher/teachers.html.j2", teachers=select_teachers, username=username
        )
    return redirect(url_for("dashboard"))


@teachers_page.route("/create_teacher", methods=["GET", "POST"])
def create_teacher():
    """Create teacher route that creates a teacher and inserts it into the database"""
    if session["is_admin"] == 1:
        teacher_model = TeacherModel(DATABASE_FILE)
        teacher_form = TeacherForm()
        bcrypt = Bcrypt()
        username = session["user"]
        if teacher_form.validate_on_submit():
            display_name = teacher_form.display_name.data
            username = teacher_form.username.data
            teacher_password = teacher_form.teacher_password.data
            is_admin = teacher_form.is_admin.data

            hashed_password = bcrypt.generate_password_hash(teacher_password)

            teacher_model.insert_teacher(
                display_name=display_name,
                username=username,
                teacher_password=hashed_password,
                is_admin=is_admin,
            )

            return redirect(url_for("teachers.teachers"))
        return render_template(
            "teacher/create_teacher.html.j2", username=username, form=teacher_form
        )
    return redirect(url_for("dashboard"))


@teachers_page.route("/delete_teacher", methods=["GET", "POST"])
def delete_teacher():
    """Delete teacher route that deletes a specific teacher from the database"""
    if session["is_admin"] == 1:
        teacher_model = TeacherModel(DATABASE_FILE)
        if request.method == "POST":
            try:
                teacher_id = request.form["teacher_id"]
                teacher_model.delete_teacher(teacher_id=teacher_id)

            except Error as error:
                print(error)

        return redirect(url_for("teachers.teachers"))

    return redirect(url_for("dashboard"))


@teachers_page.route("/search_teacher", methods=["GET", "POST"])
def search_teacher():
    """Searches for a specific teacher if the search value aligns with their name or username and
    selects them from the database"""
    if session["is_admin"] == 1:
        result = None
        teacher_model = TeacherModel(DATABASE_FILE)
        username = session["user"]
        select_teachers = teacher_model.get_all_teachers()
        if request.method == "POST":
            try:
                search_value = request.form["search_value"]

                result = teacher_model.search_teacher(search_value=search_value)
            except Error as error:
                print(error)

        return render_template(
            "teacher/teachers.html.j2",
            result=result,
            teachers=select_teachers,
            username=username,
        )
    return redirect(url_for("login"))


@teachers_page.route("/edit_teacher", methods=["POST", "GET"])
def edit_teacher():
    """Edit teacher route that edits the changed fields from the teacher into the database"""
    if session["is_admin"] == 1:
        bcrypt = Bcrypt()
        teacher_model = TeacherModel(DATABASE_FILE)
        if request.method == "POST":
            try:
                display_name = request.form["display_name"]
                username = request.form["username"]
                teacher_password = request.form["teacher_password"]
                is_admin = request.form["is_admin"]
                teacher_id = request.form["teacher_id"]
                hashed_password = bcrypt.generate_password_hash(teacher_password)
                teacher_model.update_teacher(
                    display_name=display_name,
                    username=username,
                    teacher_password=hashed_password,
                    is_admin=is_admin,
                    teacher_id=teacher_id,
                )
            except Error as error:
                print(error)

        return redirect(url_for("teachers.teachers"))

    return redirect(url_for("login"))


@teachers_page.route("/profile", methods=["GET", "POST"])
def profile():
    if "user" in session:
        admin = session["is_admin"]
        display_name = session["display_name"]
        username = session["user"]

        return render_template(
            "teacher/profile.html.j2",
            display_name=display_name,
            username=username,
            admin=admin,
        )


@teachers_page.route("/teacher/<int:teacher_id>", methods=["POST", "GET"])
def teacher(teacher_id):
    if session["is_admin"] == 1:
        selected_teacher = None
        teacher_model = TeacherModel(DATABASE_FILE)
        username = session["user"]
        if request.method == "POST":
            try:
                teacher_id = request.form["teacher_id"]
                selected_teacher = teacher_model.select_teacher(teacher_id=teacher_id)
            except Error as error:
                print(error)
        return render_template(
            "teacher/teacher.html.j2",
            teacher=selected_teacher,
            teacher_id=teacher_id,
            username=username,
        )

    return redirect(url_for("login"))

views/question.py
from flask import Blueprint, session, render_template, redirect, url_for

from controllers.questions_controller import QuestionsController

questions_page = Blueprint("questions", __name__, url_prefix="/questions", template_folder="templates/question",
                           static_folder="static")

@questions_page.route("/", methods=["GET", "POST"])
def questions():
    if "user" in session:
        username = session["user"]
        question_controller = QuestionsController()
        questions = question_controller.select_questions()

        return render_template("question/questions.html.j2", questions=questions, username=username)
    else:
        redirect(url_for("login"))

templates/beheer.html.j2
{% extends "index.html.j2" %}
{% block content %}
<div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div
        class="flex sm:flex-row flex-col space-y-2 sm:space-x-2 flex-row w-full items-center justify-center min-h-screen">
        <div
            class='flex flex-wrap flex-row sm:flex-col justify-center items-center w-full sm:w-1/4 p-5 bg-white rounded-md border'>
            <div class="flex justify-between w-full">
                <div>
                    <div class="p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-6 h-6">
                        </svg>
                    </div>
                </div>
                <div>
                    <div style="padding-top: 0.1em; padding-bottom: 0.1rem"
                        class="flex items-center text-xs px-3 bg-white-200 text-green-800 rounded-lg">
                    </div>
                </div>
            </div>
            <div>
                <div class="font-bold text-5xl">
                    {{ counted_teacher }}
                </div>
                <div class="font-bold text-sm">
                    Teachers
                </div>
            </div>
        </div>
        <div
            class='flex flex-wrap flex-row sm:flex-col justify-center items-center w-full sm:w-1/4 p-5 bg-white rounded-md border'>
            <div class="flex justify-between w-full">
                <div>
                    <div class="p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-6 h-6">
                        </svg>
                    </div>
                </div>
                <div>
                    <div style="padding-top: 0.1em; padding-bottom: 0.1rem"
                        class="flex items-center text-xs px-3 bg-white-200 text-green-800 rounded-full"></div>
                </div>
            </div>
            <div >
                <div class="font-bold text-5xl text-center">
                    {{ counted_note }}
                </div>
                <div class="font-bold text-sm">
                    Notes
                </div>
            </div>
        </div>
        <div
            class='flex flex-wrap flex-row sm:flex-col justify-center items-center w-full sm:w-1/4 p-5 bg-white rounded-md border'>
            <div class="flex justify-between w-full">
                <div>
                    <div class="p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-6 h-6">
                        </svg>
                    </div>
                </div>
                <div>
                    <div style="padding-top: 0.1em; padding-bottom: 0.1rem"
                        class="flex items-center text-xs px-3 bg-white-200 text-green-800 rounded-full"></div>
                </div>
            </div>
            <div>
                <div class="font-bold text-5xl text-center">
                    {{ counted_categories }}
                </div>
                <div class="font-bold text-sm">
                    Categories
                </div>
            </div>
        </div>
        <div
            class='flex flex-wrap flex-row sm:flex-col justify-center items-center w-full sm:w-1/4 p-5 bg-white rounded-md border'>
            <div class="flex justify-between w-full">
                <div>
                    <div class="p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-6 h-6">
                        </svg>
                    </div>
                </div>
                <div>
                    <div style="padding-top: 0.1em; padding-bottom: 0.1rem"
                        class="flex items-center text-xs px-3 bg-white-200 text-green-800 rounded-full"></div>
                </div>
            </div>
            <div>
                <div class="font-bold text-5xl text-center">
                    {{ counted_question }}
                </div>
                <div class="font-bold text-sm">
                    Questions
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html.j2
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="text-sm">
        <nav class="bg-white shadow-md mt-1">
            <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
                <div class="relative flex h-16 items-center justify-between">
                    <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                        <div class="flex flex-shrink-0 items-center">
                            <img class="h-12 w-auto" src="/static/test_correct.png" alt="Workflow">
                        </div>
                        <div class="hidden sm:ml-6 sm:block">
                            <div class="flex space-x-4 mt-1">
                                <a href="{{ url_for('dashboard') }}" class="text-blue-700 hover:bg-blue-700 hover:text-white rounded-md px-3 py-2 font-medium">Dashboard</a>
                                <a href="{{ url_for('notes.notes') }}" class="text-blue-700 hover:bg-blue-700 hover:text-white rounded-md px-3 py-2 font-medium">Notes</a>
                                <a href="{{ url_for('category.categories') }}" class="text-blue-700 hover:bg-blue-700 hover:text-white rounded-md px-3 py-2 font-medium">Categories</a>
                                {% if session["is_admin"] == 1 %}
                                    <a href="{{ url_for('teachers.teachers') }}" class="text-blue-700 hover:bg-blue-700 hover:text-white rounded-md px-3 py-2 font-medium">Teachers</a>
                                {% else %}
                                {% endif %}
                                <a href="{{ url_for('questions.questions') }}" class="text-blue-700 hover:bg-blue-700 hover:text-white rounded-md px-3 py-2 font-medium">Questions</a>
                            </div>
                        </div>
                    </div>
                    <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
                        <p  class="relative text-md p-1 text-black focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
                            Welcome
                        <p class="text-blue-500">
                            <a href="{{ url_for("teachers.profile") }}" class="hover:underline">
                                {{ username }}
                            </a>
                        </p>
                        <p  class="relative text-md p-1 text-red-500 no-underline hover:underline focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
                            <a href="{{ url_for("logout") }}">Logout</a>
                        </p>
                        <!-- Profile dropdown -->
                        <div class="relative ml-3">
                            <div>
                                <button type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                                <span class="absolute -inset-1.5"></span>
                                <span class="sr-only">Open user menu</span>
                                <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                                </button>
                            </div>
                            <!--
                                Dropdown menu, show/hide based on menu state.

                                Entering: "transition ease-out duration-100"
                                  From: "transform opacity-0 scale-95"
                                  To: "transform opacity-100 scale-100"
                                Leaving: "transition ease-in duration-75"
                                  From: "transform opacity-100 scale-100"
                                  To: "transform opacity-0 scale-95"
                                -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- Mobile menu, show/hide based on menu state. -->
            <div class="sm:hidden" id="mobile-menu">
                <div class="space-y-1 px-2 pb-3 pt-2">
                    <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                    <a href="#" class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" aria-current="page">Dashboard</a>
                    <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Team</a>
                    <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Projects</a>
                    <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Calendar</a>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/login.html.j2
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="text-sm">
        <div class="min-h-screen flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
            <div class="max-w-md w-full space-y-8">
                <div>
                    <img class="mx-auto h-12 w-auto" src="../static/test_correct.png" alt="Workflow">
                    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                        Sign in to your account
                    </h2>
                </div>
                <form class="mt-8 space-y-6" action="{{ url_for('login') }}"  method="POST">
                    <input type="hidden" name="remember" value="true">
                    <div class="rounded-md shadow-sm -space-y-px">
                        <div>
                            <label for="username" class="sr-only">Username</label>
                            <input id="username" name="username" type="text" required class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-lg focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Username">
                        </div>
                        <div>
                            <label for="password" class="sr-only">Password</label>
                            <input id="password" name="password" type="password" required class="appearance-none relative block w-full mt-2 px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-lg focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Password">
                        </div>
                    </div>

                    <div>
                        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-green-500 hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">
                            <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                                <!-- Heroicon name: solid/lock-closed -->
                            </span>
                            Sign in
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>